      - name: Fetch Sofascore JSON
        run: |
          import requests, datetime, json, os
          
          # JST (UTC+9)
          today = (datetime.datetime.utcnow() + datetime.timedelta(hours=9)).strftime("%Y-%m-%d")
          url = f"https://www.sofascore.com/api/v1/sport/football/scheduled-events/{today}"
          headers = {
              "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
          }
          
          r = requests.get(url, headers=headers)
          print("Status code:", r.status_code)
          print("URL fetched:", url)
          
          os.makedirs("data", exist_ok=True)
          if r.ok:
              data = r.json()
              with open("data/today.json", "w", encoding="utf-8") as f:
                  json.dump(data, f, indent=2, ensure_ascii=False)
          else:
              with open("data/today.json", "w") as f:
                  f.write("{}")  # empty JSON if failed
